# 1. Имя нашего автоматического конвейера
name: My First CI Pipeline

# 2. Триггер: при каком событии запускать робота?
# Говорим: запускай конвейер при каждом отправлении (push) в главную ветку main
on:
  push:
    branches: [ main ]

# 3. Сами задания (jobs), которые должен выполнить робот
jobs:
  say-hello-job:
    # Приказываем GitHub выделить нам бесплатный виртуальный сервер на базе Ubuntu
    runs-on: ubuntu-latest

    # Шаги, которые робот выполнит внутри этого сервера по очереди
    steps:
      - name: Шаг 1. Поприветствовать Сашу
        run: echo "Привет, Саша! Робот CI/CD успешно запущен в облаке GitHub!"

      - name: Шаг 2. Вывести текущую дату
        run: date
